spring:
  main:
    banner-mode: 'OFF'
  profiles:
    active: dev
  jooq:
    sql-dialect: mysql
security:
  basic:
    enabled: false
management:
  context-path: /manage

app.jwt.secret: qwerty
---
spring:
  profiles: dev
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:./db/dev;MODE=MySQL
    username: sa
    password:
---
spring:
  profiles: dev2
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot-angular2-tutorial
    username: root
    password:
logging:
  config: classpath:logback-prod.xml
---
spring:
  profiles: test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
---
spring:
  profiles: stg
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ENDPOINT}/ebdb?useSSL=false
    username: micropostuser
    password: ENC(jSxIbUwZQ5KgQJkOLGbYsZV83hH3oI0D)
logging:
  config: classpath:logback-prod.xml
app.jwt.secret: ENC(L4Y4hVbkFgZC3VFVWH28jTiCSSCBAx6xeM/nBSIahjrbc/JggbhTiKr2w9RLu9sx)
---
spring:
  profiles: prod
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ENDPOINT}/ebdb?useSSL=false
    username: micropostuser
    password: ENC(eKw2P1jyrqKKs6KVg9Ql9iaJC8ve2kD8)
logging:
  config: classpath:logback-prod.xml
app.jwt.secret: ENC(t0NojUi8WhsSCti12Qj8CgzzrBA1Wt0PC9R1N5KvRltEcegGhxSy1zEmI7OxqzOA)

